name: Regression Tests Execution

on:
  workflow_dispatch:

jobs:
  regression-job:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
        continue-on-error: true

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - run: npm install -g allure-commandline && npx playwright install --with-deps

      - name: Restore Regression History
        run: |
          mkdir -p target/allure-results/history
          if [ -d gh-pages/allure-history/regression/history ]; then
            cp -r gh-pages/allure-history/regression/history/* target/allure-results/history/
          fi

      - name: Run Regression
        id: run
        continue-on-error: true
        run: xvfb-run --auto-servernum -- mvn clean test -Dcucumber.filter.tags="@regression"

      - name: Generate Defect Age + Report
        if: always()
        run: |
          mvn exec:java -Dexec.mainClass="com.samtech.qa.testutilities.AllureDefectAge" -Dexec.classpathScope=test
          allure generate target/allure-results -o allure-report-regression --clean

      - name: Update gh-pages Content
        if: always()
        run: |
          mkdir -p gh-pages/regression-report
          mkdir -p gh-pages/allure-history/regression

          rm -rf gh-pages/regression-report/*
          cp -r allure-report-regression/* gh-pages/regression-report/
          rm -rf gh-pages/allure-history/regression/history
          cp -r allure-report-regression/history gh-pages/allure-history/regression/

      - name: Deploy to gh-pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
          publish_branch: gh-pages
          keep_files: true

      - name: Final Status
        if: always()
        run: exit ${{ steps.run.outcome == 'failure' && 1 || 0 }}
